[project]
name = "testtravelwebsiteproject"
version = "0.1.0"
description = ""
authors = [
    {name = "Simmy",email = "simmyabi13@gmail.com"}
]
readme = "README.md"
[tool.poetry.dependencies]
python = "3.12.5"
selenium = "4.29.0"
pytest = "7.4.0"
junit-xml = "1.9"
pytest-html = "3.2.0"
